name: Build and test

on:
  push:
    branches:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        name: [ linux-gcc-c++17,
                linux-gcc-c++20,
                linux-clang-c++17,
                linux-clang-c++20,
                windows
                ]
        include:
          - name: linux-gcc-c++17
            compiler: gcc
            std: c++17
            os: ubuntu-latest

          - name: linux-gcc-c++20
            compiler: gcc
            std: c++20
            os: ubuntu-latest
            
          - name: linux-clang-c++17
            compiler: clang
            std: c++17
            os: ubuntu-latest

          - name: linux-clang-c++20
            compiler: clang
            std: c++20
            os: ubuntu-latest

          - name: windows
            compiler: idk
            std: c++20
            os: ubuntu-latest
            arch: win64

    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image || '' }}
    steps:
    - uses: actions/checkout@v4

    - name: Install (Linux)
      run: |
        sudo apt-get install -y ccache meson cmake

    - name: Install (Windows)
      if: matrix.name == 'windows'
      run: |
        sudo apt-get install -y ccache meson cmake
        sudo apt-get install -y git python3-setuptools python3-pip g++-mingw-w64 wine64
        ${GITHUB_WORKSPACE}/scripts/make_winroot.sh -ccache true

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
         key: ${{ matrix.name }}
         restore-keys: |
           ${{ matrix.name }}

    - name: Set variables
      run: |
        if [ "${{ matrix.compiler }}" = clang ] ; then
            echo CC=clang >> $GITHUB_ENV
            echo CXX=clang++ >> $GITHUB_ENV
        fi
        echo CXXFLAGS=-std=${{ matrix.std }} >> $GITHUB_ENV
           
    - name: Build and test with meson
      run: |
        if [ "${{ matrix.name }}" = "windows" ] ; then
          margs="--cross-file=win64-cross.txt"
        fi
        meson setup mbuild ${margs}
        cd mbuild
        ninja
        if [ "${{ matrix.name }}" != "windows" ] ; then
          ninja test
        fi

    - name: Build and install and test with autoconf
      if: matrix.name != 'windows'
      run: |
        ./bootstrap.sh
        cd ../
        mkdir build
        cd build
        ../ncl/configure --prefix=$HOME/local
        make -j4
        make check
        make install
        make installcheck
