name: Build and test

on:
  push:
    branches:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        name: [ linux-gcc-c++17,
                linux-gcc-c++20,
                linux-clang-c++17,
                linux-clang-c++20 ]
        include:
          - name: linux-gcc-c++17
            compiler: gcc
            std: c++17
            os: ubuntu-latest

          - name: linux-gcc-c++20
            compiler: gcc
            std: c++20
            os: ubuntu-latest
            
          - name: linux-clang-c++17
            compiler: clang
            std: c++17
            os: ubuntu-latest

          - name: linux-clang-c++20
            compiler: clang
            std: c++20
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image || '' }}
    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: |
        sudo apt-get install -y ccache meson cmake

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
         key: ${{ matrix.name }}
         restore-keys: |
           ${{ matrix.name }}

    - name: Set variables
      run: |
        if [ "${{ matrix.compiler }}" = clang ] ; then
            echo CC=clang >> $GITHUB_ENV
            echo CXX=clang++ >> $GITHUB_ENV
        fi
        echo CXXFLAGS=-std=${{ matrix.std }} >> $GITHUB_ENV
           
    - name: Build and test with meson
      run: |
        meson setup mbuild
        cd mbuild
        ninja
        ninja test

    - name: Build and install and test with cmake
      run: |
        ./bootstrap.sh
        cd ../
        mkdir build
        cd build
        ../ncl/configure --prefix=$HOME/local
        make -j4
        make check
        make install
        make installcheck
